query LegacySubtitleSearch($tmdb_id: String!, $language: String!, $media_type: String!)
{
    legacySubtitleSearch(tmdb_id: $tmdb_id, language: $language, media_type: $media_type){
        entries{
            SubHash
            SubFileName
            SubDownloadLink
            ZipDownloadLink
            SubtitlesLink
            SubRating
            SubFormat
            LanguageName
        }
    }
}
