var DEFAULT_SUBTITLE_SEARCH_RESULT = [
    {
        "SubActualCD": "3",
        "MovieName": "Pulp Fiction",
        "SubBad": "0",
        "MovieHash": "0",
        "SubFileName": "Pulp_Fiction_(DivX_DVDrip)_-_CD_2.English.srt",
        "SubSumCD": "4",
        "ZipDownloadLink": "http://dl.opensubtitles.org/en/download/src-api/vrf-e95e0b77/sid-H,ss3bi0urTf7bOhtZYm6QXciu4/subad/113540",
        "MovieNameEng": "",
        "SubSize": "63902",
        "IDSubtitleFile": "154506",
        "SubHash": "d78540d4c71a86ead6e832699b563216",
        "SubFeatured": "0",
        "SubAuthorComment": "",
        "SubDownloadsCnt": "533",
        "SubAddDate": "2005-03-01 00:00:00",
        "SubLastTS": "00:58:50",
        "SubAutoTranslation": "0",
        "MovieReleaseName": "Pulp Fiction",
        "SeriesIMDBParent": "0",
        "UserNickName": "original_masken (a)",
        "SubHearingImpaired": "0",
        "SubTSGroup": "79",
        "SubLanguageID": "eng",
        "SubFormat": "srt",
        "LanguageName": "English",
        "SubTranslator": "",
        "SeriesEpisode": "0",
        "UserRank": "bronze member",
        "MovieImdbRating": "8.9",
        "MovieTimeMS": "0",
        "MovieYear": "1994",
        "SubEncoding": "ASCII",
        "QueryNumber": "0",
        "SubHD": "0",
        "UserID": "39934",
        "MovieByteSize": "0",
        "MovieFPS": "0.000",
        "SubtitlesLink": "http://www.opensubtitles.org/en/subtitles/113540/sid-H,ss3bi0urTf7bOhtZYm6QXciu4/pulp-fiction-en",
        "IDSubMovieFile": "0",
        "ISO639": "en",
        "SeriesSeason": "0",
        "SubFromTrusted": "0",
        "SubTSGroupHash": "2b63fa88c9cdee2f225fbcb20939f9c6",
        "MatchedBy": "imdbid",
        "SubDownloadLink": "http://dl.opensubtitles.org/en/download/src-api/vrf-e9740b7e/sid-H,ss3bi0urTf7bOhtZYm6QXciu4/filead/154506.gz",
        "SubRating": "0.0",
        "QueryParameters": {
            "imdbid": "0110912",
            "sublanguageid": "eng"
        },
        "SubComments": "0",
        "MovieKind": "movie",
        "IDMovie": "60",
        "IDMovieImdb": "110912",
        "SubForeignPartsOnly": "0",
        "IDSubtitle": "113540"
    },
    {
        "SubActualCD": "2",
        "MovieName": "Pulp Fiction",
        "SubBad": "0",
        "MovieHash": "0",
        "SubFileName": "Pulp_Fiction_(DivX_DVDrip)_-_CD_1.Swedish.srt",
        "SubSumCD": "4",
        "ZipDownloadLink": "http://dl.opensubtitles.org/en/download/src-api/vrf-e95e0b77/sid-H,ss3bi0urTf7bOhtZYm6QXciu4/subad/113540",
        "MovieNameEng": "",
        "SubSize": "65320",
        "IDSubtitleFile": "154507",
        "SubHash": "93576df6508d13e3b76da6f0d8f00f9e",
        "SubFeatured": "0",
        "SubAuthorComment": "",
        "SubDownloadsCnt": "533",
        "SubAddDate": "2005-03-01 00:00:00",
        "SubLastTS": "01:24:24",
        "SubAutoTranslation": "0",
        "MovieReleaseName": "Pulp Fiction",
        "SeriesIMDBParent": "0",
        "UserNickName": "original_masken (a)",
        "SubHearingImpaired": "0",
        "SubTSGroup": "36",
        "SubLanguageID": "eng",
        "SubFormat": "srt",
        "LanguageName": "English",
        "SubTranslator": "",
        "SeriesEpisode": "0",
        "UserRank": "bronze member",
        "MovieImdbRating": "8.9",
        "MovieTimeMS": "0",
        "MovieYear": "1994",
        "SubEncoding": "ASCII",
        "QueryNumber": "0",
        "SubHD": "0",
        "UserID": "39934",
        "MovieByteSize": "0",
        "MovieFPS": "0.000",
        "SubtitlesLink": "http://www.opensubtitles.org/en/subtitles/113540/sid-H,ss3bi0urTf7bOhtZYm6QXciu4/pulp-fiction-en",
        "IDSubMovieFile": "0",
        "ISO639": "en",
        "SeriesSeason": "0",
        "SubFromTrusted": "0",
        "SubTSGroupHash": "5dda2ce3493edf07e9246586396e9919",
        "MatchedBy": "imdbid",
        "SubDownloadLink": "http://dl.opensubtitles.org/en/download/src-api/vrf-e9750b7f/sid-H,ss3bi0urTf7bOhtZYm6QXciu4/filead/154507.gz",
        "SubRating": "0.0",
        "QueryParameters": {
            "imdbid": "0110912",
            "sublanguageid": "eng"
        },
        "SubComments": "0",
        "MovieKind": "movie",
        "IDMovie": "60",
        "IDMovieImdb": "110912",
        "SubForeignPartsOnly": "0",
        "IDSubtitle": "113540"
    }
];


exports.DEFAULT_SUBTITLE_SEARCH_RESULT = DEFAULT_SUBTITLE_SEARCH_RESULT;
