#import "@/search/subtitleSearchFragment.gql"
query SubtitleSearchForSeries($tmdb_id: String!, $language: String!, $season_number: Int, $episode_number: Int)
{
    subtitleSearch(tmdb_id: $tmdb_id, language: $language, season_number: $season_number, episode_number: $episode_number){
        ...SubtitleSearchFragmentResult
    }

    seasons(tmdb_id: $tmdb_id, language: $language) {
        seasons {
            episode_count
            season_number
        }
    }
}
